### ISSUE TITLE
Compiling using g++

### ISSUE THREAD

**Issue by swindmill** [babun/babun#191]
I seem to be having the same issue documented here in babun:

http://stackoverflow.com/questions/19642787/netbeans-and-c-installation

But it is not clear how to downgrade a package using pact. Is this possible?

Currently, the following command errors out due to a missing header file as shown below:

echo -e "#include <iostream>\n int main() { return 0; }" | g++ -xc++ -

In file included from /usr/include/wchar.h:6:0,
                 from /usr/lib/gcc/i686-pc-cygwin/4.8.3/include/c++/cwchar:44,
                 from /usr/lib/gcc/i686-pc-cygwin/4.8.3/include/c++/bits/postypes.h:40,
                 from /usr/lib/gcc/i686-pc-cygwin/4.8.3/include/c++/iosfwd:40,
                 from /usr/lib/gcc/i686-pc-cygwin/4.8.3/include/c++/ios:38,
                 from /usr/lib/gcc/i686-pc-cygwin/4.8.3/include/c++/ostream:38,
                 from /usr/lib/gcc/i686-pc-cygwin/4.8.3/include/c++/iostream:39,
                 from <stdin>:1:
/usr/include/sys/reent.h:14:20: fatal error: stddef.h: No such file or directory
 #include <stddef.h>
                    ^
compilation terminated.

**Comment by tombujok** [comment]
Please retry after upgrading babun to 1.1.0 (just execute babun update)

**Comment by stelioschar** [comment]
the problem stills exists with v1.1.1 in windows 8.1.

I tried to run [this tutorial](http://blog.eisele.net/2015/06/docker-compose-on-windows-with-python.html) and I get a warning 'InsecurePlatformWarning from python'. 

According to [this post](http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package) I need to run ```pip install requests[security]``` in order to solve my issue and I get the error below:

```
Installing collected packages: cffi, cryptography, pyOpenSSL, ndg-httpsclient
  Running setup.py install for cffi
    Complete output from command /usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-A4qBWQ/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Owyelt-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running install
    running build
    running build_py
    running build_ext
    building '_cffi_backend' extension
    gcc -fno-strict-aliasing -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python/python-2.7.8-1.i686/build=/usr/src/debug/python-2.7.8-1 -fdebug-prefix-map=/usr/src/ports/python/python-2.7.8-1.i686/src/Python-2.7.8=/usr/src/debug/python-2.7.8-1 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.cygwin-1.7.35-i686-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-A4qBWQ/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Owyelt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-A4qBWQ/cffi
```

Any idea/help?

**Comment by bmhaskar** [comment]
@stelioschar I am facing exact same issue: I am trying to install docker-compose with babun  and I landed into this.

**Comment by bmhaskar** [comment]
`pact  install libffi-devel`   seems to work  in my case.

**Comment by stelioschar** [comment]
@bmhaskar this resolved the 'gcc' failure :+1: thank you!

**Comment by hs366** [comment]
I had the same issue with gcc and g++ and solved by : pact update gcc-core gcc-g++
source: https://kevinlyu.blogspot.se/2016/06/babun-compile-with-g.html

**Comment by hs366** [comment]
which package do i need to install if i want to compile in g++ -std=c++11 ? 
here is my gcc and g++ version: 
gcc version 5.4.0 (GCC)
and here is my packaged installed: [pact show](https://gist.github.com/hs366/7a243003714a0f18b2f60cd1b94347f7#file-installed-packages)

**Comment by cronkenstein** [comment]
@hs366 I have been trying to figure out this problem since early September and what I found is that we need to update cygwin-devel alongside the GCC 5.4 update. All I had to do was `pact update cygwin-devel`

**Comment by hs366** [comment]
@cronkenstein thx for reply. I decided not using Babun anymore, maybe its a good tool but not for me i prefer something more state forward and pure.

**Comment by sayo9394** [comment]
@cronkenstein thanks heaps! your solution (as well as the pact update gcc-core gcc-g++) fixed the problem :+1:
